bash := if os_family() == 'windows' {
    'C:\\PROGRA~1\Git\\usr\\bin\\bash.exe'
} else {
    '/usr/bin/env bash'
}

module := 'cmdargs'

test:
    #!{{bash}}
    go test ./...

bump:
    #!{{bash}}
    deno run -A ../bin/publish.ts {{module}} --bump --patch

bump-minor:
    #!{{bash}}
    deno run -A ../bin/publish.ts {{module}} --bump --minor
bump-major:
    #!{{bash}}
    deno run -A ../bin/publish.ts {{module}} --bump --major

tag:
    #!{{bash}}
    deno run -A ../bin/publish.ts {{module}} --tag
    